language: php

php:
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php composer.phar style

notifications:
  email:
    on_failure: change

sudo: false
