name: "🐛 Bug Report"
description: If something isn't working as expected
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: A clear and concise description of the behavior.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: The exact steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error message '....'
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: |
        - Flarum version: x.y.z
        - Website URL: http://example.com
        - Webserver: [e.g. apache, nginx]
        - Hosting environment: [e.g. shared, vps]
        - PHP version: x.y.z
        - Browser: [e.g. chrome 67, safari 11]
    validations:
      required: true
  - type: textarea
    id: php_flarum_info
    attributes:
      label: "Output of `php flarum info`"
      value: |
        ```
        Output of "php flarum info", run this in terminal in your Flarum directory.
        ```
    validations:
      required: false
  - type: textarea
    id: possible_solution
    attributes:
      label: Possible Solution
      description: Only if you have suggestions or a fix for the bug.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
