name: "🚀 Feature Request"
description: If you have a suggestion/proposal to improve Flarum.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        We primarily use GitHub as a bug tracker and issue tracker for items we are sure to tackle in the near future.
        For feature requests, ideas and feedback please post in the Flarum Community: https://discuss.flarum.org/t/proposals.
        Feature requests are added to GitHub only when they have been accepted by the development team and implementation details have been laid out.
