name: "🙋‍ Support Question"
description: If you have a question, please check out our forum or Discord!
body:
  - type: markdown
    attributes:
      value: |
        We primarily use GitHub as a bug tracker and issue tracker for items we are sure to tackle in the near future; for usage and support questions, please check out these resources below. Thanks!

        * Flarum Community: https://discuss.flarum.org/
        * Discord Chat: https://flarum.org/discord/
        * Twitter: https://twitter.com/Flarum
