language: minimal

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    - stage: build
      if: branch = master AND type = push
      script: curl -s https://raw.githubusercontent.com/flarum/core/master/.travis/build.sh | bash -s -
        -k $encrypted_5d7262885acd_key
        -i $encrypted_5d7262885acd_iv
