name: JavaScript

on:
  push:
    branches:
      - master

jobs:
  build:
    name: JS / Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build production JS
        uses: flarum/action-build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
