name: Lint

on:
  workflow_dispatch:
  push:
    paths:
      - 'js/src/**'
  pull_request:
    paths:
      - 'js/src/**'

jobs:
  prettier:
    name: JS / Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check JS formatting
        run: npx prettier --check src
        working-directory: ./js
