name: Suspend JS

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: ./.github/workflows/REUSABLE_frontend.yml
    with:
      enable_bundlewatch: false
      enable_prettier: true
      enable_typescript: false

      frontend_directory: ./extensions/suspend/js
      backend_directory: ./extensions/suspend
      js_package_manager: yarn
      main_git_branch: main

    secrets:
      bundlewatch_github_token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
