name: Core JS

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: ./.github/workflows/REUSABLE_frontend.yml
    with:
      enable_bundlewatch: true
      enable_prettier: true
      enable_typescript: true

      frontend_directory: ./framework/core/js
      backend_directory: ./framework/core
      js_package_manager: yarn
      main_git_branch: main

    secrets:
      bundlewatch_github_token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
