name: Tags JS

on: [workflow_dispatch, push, pull_request]

# The reusable workflow definitions will be moved to the `flarum/framework` repo soon.
# This will break your current script.
# When this happens, run `flarum-cli audit infra --fix` to update your infrastructure.

jobs:
  run:
    uses: ./.github/workflows/REUSABLE_frontend.yml
    with:
      enable_bundlewatch: false
      enable_prettier: false
      enable_typescript: true

      frontend_directory: ./extensions/tags/js
      backend_directory: ./extensions/tags
      js_package_manager: yarn
      main_git_branch: main
    secrets:
      bundlewatch_github_token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
