name: Subscriptions JS

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: ./.github/workflows/REUSABLE_frontend.yml
    with:
      enable_bundlewatch: false
      enable_prettier: true
      enable_typescript: false

      frontend_directory: ./extensions/subscriptions/js
      backend_directory: ./extensions/subscriptions
      js_package_manager: yarn
      cache_dependency_path: ./yarn.lock
      main_git_branch: main

    secrets:
      bundlewatch_github_token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
