name: Frontend Workflow

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: ./.github/workflows/REUSABLE_frontend.yml
    with:
      frontend_directory: ./
      backend_directory: ./
      js_package_manager: yarn
      cache_dependency_path: ./yarn.lock
      main_git_branch: main
      enable_tests: true
      # @TODO: fix bundlewatch
      enable_bundlewatch: false

    secrets:
      bundlewatch_github_token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
