name: JS

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/.github/.github/workflows/REUSABLE_frontend.yml@main
    with:
      main_git_branch: master
    secrets:
      bundlewatch_github_token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}