name: JS

on: [workflow_dispatch, push, pull_request]

env:
  NODE_VERSION: 16

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: js/yarn.lock

      - name: Install JS dependencies
        run: yarn install --immutable
        working-directory: ./js

      - name: Check JS formatting
        run: yarn run format-check
        working-directory: ./js

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: js/yarn.lock

      - name: Install JS dependencies
        run: yarn --frozen-lockfile
        working-directory: ./js

      - name: Typecheck
        run: yarn run check-typings || true  # REMOVE THIS ONCE TYPE SAFETY REACHED
        working-directory: ./js

  type-coverage:
    name: Type Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: js/yarn.lock

      - name: Install JS dependencies
        run: yarn --frozen-lockfile
        working-directory: ./js

      - name: Check type coverage
        run: yarn run check-typings-coverage
        working-directory: ./js

  build-prod:
    name: Build and commit
    runs-on: ubuntu-latest
    needs: [prettier, typecheck, type-coverage]

    # Only commit JS on push to master branch
    # Remember to change in `build-test` job too
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: js/yarn.lock

      # Our action will install npm, cd into `./js`, run `npm run build` and
      # `npm run build-typings`, then commit and upload any changes
      - name: Build production JS
        uses: flarum/action-build@2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build
          package_manager: yarn
          typings_script: build-typings

  build-test:
    name: Test build
    runs-on: ubuntu-latest
    needs: [prettier, typecheck, type-coverage]

    # Inverse check of `build-prod`
    # Remember to change in `build-prod` job too
    if: github.ref != 'refs/heads/master' || github.event_name != 'push'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: js/yarn.lock

      # Our action will install npm, cd into `./js`, run `npm run build` and
      # `npm run build-typings`, then commit and upload any changes
      - name: Build production JS
        uses: flarum/action-build@2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build
          package_manager: yarn
          typings_script: build-typings
          do_not_commit: true
