name: Static Code Analysis

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: ./.github/workflows/REUSABLE_backend.yml
    with:
      enable_backend_testing: false
      enable_phpstan: true
      backend_directory: .
