name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Prepare release
        uses: flarum/action-release@master
        with:
          next_tag: ${{ inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          open_collective_token: ${{ secrets.OPEN_COLLECTIVE_TOKEN }}
