name: Typescript Checks

on: [workflow_dispatch, push, pull_request]

env:
  NODE_VERSION: 16

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: js/package-lock.json

      - name: Install JS dependencies
        run: npm ci
        working-directory: ./js

      - name: Typecheck
        run: npm run check-typings
        working-directory: ./js

  type-coverage:
    name: Type Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: js/package-lock.json

      - name: Install JS dependencies
        run: npm ci
        working-directory: ./js

      - name: Check type coverage
        run: npm run check-typings-coverage
        working-directory: ./js
